language: node_js
node_js:
  - 0.8
install:
  - date
script:
  - ./script.sh
env:
  global:
    - secure: "NPnFHyo6KAzebxKVgiAlf543IDRTyXR5ZL1cnuQ09q0BJmC+iSgcB6TIcy+v\n+Z8ik/2zsYahMx55SO0nmXQE1H/RWNYbioUivR3invdCII99LvfAtTPdAT08\nO2jYNbHJ+RAUU20bd4e2l+4hPYNKypuZxWhI+rsfKSSD3ElJ+B8="